name: PointsCommands
main: top.mymoe.pointscommands.PointsCommands
version: 1.0.2
author: GiNYAi
description: A simple plugin.
softdepend: [PlayerPoints,PlaceholderAPI]
commands:
  PointsCommands:
    description: The commands of PointsCommands.
    permission: pointscommands.command